import subprocess

trusted_packages = ['me.bmax.apatch']
trust_package_namespace = 'trusted_app_linearity'
out = []
untrusted_app_names: set[str] = set[str]()
whitelists = [
    'servicemanager_prop',
    'hwservicemanager_prop',
]

blacklist_tag_contains: set[str] = {
    'proc_',
    '_proc',
    'virtualizationmanager',
    'keystore_',
    '_prop',
    'init_exec',
    'zygote',
    'magisk',
    'property',
    'unencrypted',
}
blacklist_tags: set[str] = {
    'apc_service',
    'nfc_service',
    'drmserver_service',
    'hal_drm_service',
    'hal_drm_server',
    'hal_cas_service',
    'hal_cas_server',
    'usb_device',
    # 'radio_service',#sms send message needs to get sim
    'keystore_service',#oneday i'll block this if only i can define my own context
    'credstore_service',
    'lineage_profile_service',

    # 'privapp_data_file',
    'crash_dump',
    'hal_drm_hwservice',
    'sysfs_thermal',
    'vendor_file',
    'hidl_memory_hwservice',
    'adb_data_file',
    'adbroot_data_file',
    'init',
    'rootfs',
    'vendor_configs_file',
    'magisk_file',
    'adb_service',
    'adbroot_service',
    # 'sdcard_type',
    # 'su',

    'system_app_data_file',
    'asec_apk_file',
    'sdk_sandbox_data_file',
    'mnt_vendor_file',


    'aac_drc_prop',
    'aaudio_config_prop',
    'ab_update_gki_prop',
    'accessibility_trace_data_file',
    'aconfig_storage_flags_metadata_file',
    'aconfig_storage_metadata_file',
    'aconfigd_exec',
    'adaptive_haptics_prop',
    'adb_data_file',
    'adb_keys_file',
    'adbd_config_prop',
    'adbd_exec',
    'adbd_prop',
    'adbd_socket',
    'adbroot',
    'adbroot_data_file',
    'adbroot_exec',
    'adsprpcd_file',
    'anr_data_file',
    'apex_art_data_file',
    'apex_art_staging_data_file',
    'apex_data_file',
    'apex_info_file',
    'apex_metadata_file',
    'apex_mnt_dir',
    'apex_module_data_file',
    'apex_ota_reserved_file',
    'apex_ready_prop',
    'apex_rollback_data_file',
    'apex_system_server_data_file',
    'apex_tethering_data_file',
    'apex_virt_data_file',
    'apexd_config_prop',
    'apexd_exec',
    'apexd_payload_metadata_prop',
    'apexd_prop',
    'apexd_select_prop',

    'cgroup_v2',
    'debugfs_trace_marker',
    'debugfs_tracing',
    'debugfs_tracing_debug',
    'debugfs_tracing_instances',
    'debugfs_tracing_printk_formats',
    'debugfs_wifi_tracing',
    'fs_bpf',
    'fs_bpf_loader',
    'fs_bpf_net_private',
    'fs_bpf_net_shared',
    'fs_bpf_netd_readonly',
    'fs_bpf_netd_shared',
    'fs_bpf_tethering',
    'fs_bpf_uprobestats',
    'fs_bpf_vendor',
    'fusectlfs',
    'null_device',

    'last_boot_reason_prop',
    'libc_debug_prop',
    'linkerconfig_exec',
    'linkerconfig_file',
    'lirc_device',
    'llkd_exec',
    'llkd_prop',
    'lmkd',
    'lmkd_config_prop',
    'lmkd_exec',
    'lmkd_prop',
    'lmkd_socket',
    'locale_prop',
    'localization_prop',
    'log_file_logger_prop',
    'log_prop',
    'log_tag_prop',
    'logcat_exec',
    'logd',
    'logd_auditrate_prop',
    'logd_exec',
    'logd_prop',
    'logd_socket',
    'logdr_socket',
    'logdw_socket',
    'logpersistd_logging_prop',
    'loop_control_device',
    'loop_device',
    'lower_kptr_restrict_prop',
    'lowpan_prop',
    'lpdumpd_exec',
    'lpdumpd_prop',
    'mac_perms_file',
    'magisk',
    'magisk_file',
    'mdns_socket',
    'mdnsd_exec',
    'media_config_prop',
    'media_data_file',
    # 'media_rw_data_file',
    'media_userdir_file',
    'media_variant_prop',
    'mediacodec',
    'mediacodec_exec',
    'mediadrm_config_prop',
    'mediaextractor',
    'mediaextractor_exec',
    'mediametrics',
    'mediametrics_exec',
    'mediaprovider',
    'mediaprovider_app',
    'mediaserver',
    'mediaserver_exec',
    'mediaswcodec',
    'mediaswcodec_exec',
    'mediatranscoding_exec',
    'metadata_block_device',
    'metadata_bootstat_file',
    'metadata_file',
    'method_trace_data_file',
    'migrate_legacy_obb_data_exec',
    'mirror_data_file',
    'misc_block_device',
    'misc_logd_file',
    'misc_user_data_file',
    'misctrl_exec',
    'misctrl_prop',
    'mkfs_exec',
    'mm_events_config_prop',
    'mm_events_exec',
    'mmc_prop',
    'mnt_expand_file',
    'mnt_media_rw_file',
    'mnt_pass_through_file',
    'mnt_product_file',
    'mnt_sdcard_file',
    # 'mnt_user_file',
    'mnt_vendor_file',
    'mock_ota_prop',
    'module_sdkextensions_prop',
    'motor_device',
    'mtectrl_exec',
    'mtp_device',

    'net_464xlat_fromvendor_prop',
    'net_connectivity_prop',
    'net_data_file',
    'net_dns_prop',
    'net_radio_prop',
    'netd',
    'netd_exec',
    'netd_stable_secret_prop',
    'netutils_wrapper_exec',
    'network_stack',
    'network_watchlist_data_file',
    'next_boot_prop',
    'nfc',
    'nfc_data_file',
    'nfc_device',
    'nfc_logs_data_file',
    'nfc_prop',
    'nnapi_ext_deny_product_prop',
    'null_device',

    'oatdump_exec',
    'odrefresh_data_file',
    'odrefresh_exec',
    'odsign_data_file',
    'odsign_exec',
    'odsign_metrics_file',
    'odsign_prop',
    'oem_unlock_prop',
    'ot_daemon_exec',
    'ot_daemon_socket',
    'ota_build_prop',
    'ota_data_file',
    'ota_image_data_file',
    'ota_metadata_file',
    'ota_package_file',
    'ota_prop',
    'overlay_prop',
    'overlayfs_file',
    'owntty_device',

    'packagemanager_config_prop',
    'packages_list_file',
    'pan_result_prop',
    'password_slot_metadata_file',
    'perf_drop_caches_prop',
    'perfetto_configs_data_file',
    'perfetto_exec',
    'perfetto_traces_bugreport_data_file',
    'perfetto_traces_data_file',
    'perfetto_traces_profiling_data_file',
    'permissioncontroller_app',
    'permissive_mte_prop',
    'persist_debug_prop',
    'persist_sysui_builder_extras_prop',
    'persist_sysui_ranking_update_prop',
    'persist_vendor_debug_wifi_prop',
    'persist_wm_debug_prop',
    'persistent_properties_ready_prop',
    'platform_app',
    'pm_archiving_enabled_prop',
    'pm_prop',
    'pmsg_device',
    'power_debug_prop',
    'powerctl_prop',
    'preloads_data_file',
    'prereboot_data_file',
    'priv_app',
    # 'privapp_data_file',
    'prng_seeder',
    'prng_seeder_exec',
    'prng_seeder_socket',
    # 'proc',
    'proc_abi',
    'proc_asound',
    'proc_bpf',
    'proc_buddyinfo',
    'proc_cmdline',
    'proc_cpuinfo',
    'proc_dirty',
    'proc_diskstats',
    'proc_drop_caches',
    'proc_extra_free_kbytes',
    'proc_filesystems',
    'proc_hostname',
    'proc_interrupts',
    'proc_iomem',
    'proc_kallsyms',
    'proc_keys',
    'proc_kmsg',
    'proc_kpageflags',
    'proc_loadavg',
    'proc_locks',
    'proc_max_map_count',
    'proc_meminfo',
    'proc_misc',
    'proc_modules',
    'proc_net',
    'proc_net_tcp_udp',
    'proc_overcommit_memory',
    'proc_page_cluster',
    'proc_pagetypeinfo',
    'proc_panic',
    'proc_perf',
    'proc_pid_max',
    'proc_pipe_conf',
    'proc_pressure_cpu',
    'proc_pressure_io',
    'proc_pressure_mem',
    'proc_random',
    'proc_sched',
    'proc_security',
    'proc_stat',
    'proc_swaps',
    'proc_sysrq',
    'proc_timer',
    'proc_tty_drivers',
    'proc_uid_concurrent_active_time',
    'proc_uid_concurrent_policy_time',
    'proc_uid_cputime_removeuid',
    'proc_uid_cputime_showstat',
    'proc_uid_io_stats',
    'proc_uid_procstat_set',
    'proc_uid_time_in_state',
    'proc_uptime',
    'proc_version',
    'proc_vmallocinfo',
    'proc_vmstat',
    'proc_watermark_boost_factor',
    'proc_watermark_scale_factor',
    'proc_zoneinfo',
    'profcollectd_data_file',
    'profcollectd_exec',
    'profcollectd_node_id_prop',
    'profman_dump_data_file',
    'profman_exec',
    'properties_device',
    'properties_serial',
    'property_contexts_file',
    'property_data_file',
    'property_info',
    'property_service_version_prop',
    'property_socket',
    'provisioned_prop',
    'pstorefs',
    'ptmx_device',
    'qemu_hw_prop',
    'qemu_sf_lcd_density_prop',
    'quick_start_prop',

    'radio',
    'radio_cdma_ecm_prop',
    'radio_control_prop',
    'radio_core_data_file',
    'radio_data_file',
    'radio_prop',
    'ram_device',
    'random_device',
    'rebootescrow_hal_prop',
    'recovery_block_device',
    'recovery_config_prop',
    'recovery_data_file',
    'recovery_persist_exec',
    'recovery_update_prop',
    'recovery_usb_config_prop',
    'remote_prov_prop',
    'remount_exec',
    'resourcecache_data_file',
    'restorecon_prop',
    'retaildemo_prop',
    'rild',
    'rild_exec',
    'ringtone_file',
    'rollback_data_file',
    'rollback_test_prop',
    'rootdisk_sysdev',
    'rs_exec',
    'rss_hwm_reset_exec',
    'rtc_device',
    'runas_exec',
    'runtime_event_log_tags_file',

    'safemode_prop',
    'same_process_hal_file',
    'sdcardd_exec',
    'sdcardfs',
    'sdk_sandbox_system_data_file',
    'seapp_contexts_file',
    'secure_element',
    'selinuxfs',
    'sendbug_config_prop',
    'sensors_config_prop',
    'sensors_device',
    'sepolicy_file',
    'serialno_prop',
    'server_configurable_flags_data_file',
    'service_contexts_file',
    # 'servicemanager',
    # 'servicemanager_exec',
    # 'servicemanager_prop', #stops qq from launching
    'setupwizard_mode_prop',
    'setupwizard_prop',
    'sgdisk_exec',
    'shared_relro_file',
    'shared_relro_file',
    'shell_data_file',
    'shell_exec',# apatch
    'shell_prop',
    'shell_test_data_file',
    'shortcut_manager_icons',
    'shutdown_checkpoints_system_data_file',
    'simpleperf_app_runner_exec',
    'simpleperf_exec',
    'smart_idle_maint_enabled_prop',
    'snapshotctl_exec',
    'snapshotctl_log_data_file',
    'snapuserd_exec',
    'snapuserd_prop',
    'soc_prop',
    'socket_device',
    'socket_hook_prop',
    'sqlite_log_prop',
    'staged_install_file',
    'staging_data_file',
    'stats_config_data_file',
    'stats_data_file',
    'statsd',
    'statsd_exec',
    'statsdw_socket',
    'storage_config_prop',
    'storage_file',
    'storaged',
    'storaged_data_file',
    'storaged_exec',
    'storagemanager_config_prop',
    'su',
    'super_block_device',
    'surfaceflinger',
    'surfaceflinger_color_prop',
    'surfaceflinger_display_prop',
    'surfaceflinger_exec',
    'surfaceflinger_prop',
    'suspend_debug_prop',
    'suspend_prop',
    'swap_block_device',

    # 'sysfs', # idk if it suitable
    'sysfs_android_usb',
    'sysfs_bluetooth_writable',
    'sysfs_devices_block',
    'sysfs_devices_cs_etm',
    'sysfs_devices_system_cpu',
    'sysfs_dm',
    'sysfs_dm_verity',
    'sysfs_dt_firmware_android',
    'sysfs_extcon',
    'sysfs_fs_ext4_features',
    'sysfs_fs_f2fs',
    'sysfs_fs_incfs_features',
    'sysfs_hwrandom',
    'sysfs_iio',
    'sysfs_ion',
    'sysfs_kernel_notes',
    'sysfs_leds',
    'sysfs_loop',
    'sysfs_msm_boot',
    'sysfs_net',
    'sysfs_perdev_minors',
    'sysfs_power',
    'sysfs_rtc',
    'sysfs_suspend_stats',
    'sysfs_thermal',
    'sysfs_touchpanel',
    'sysfs_uhid',
    'sysfs_uio',
    'sysfs_uprobe',
    'sysfs_usb',
    'sysfs_usermodehelper',
    'sysfs_wake_lock',
    'sysfs_wakeup',
    'sysfs_wakeup_reasons',
    'sysfs_wlan_fwpath',
    'sysfs_zram',
    'sysfs_zram_uevent',
    'system_adbd_prop',
    'system_app',
    'system_app_data_file',
    'system_app_data_file',
    'system_audio_config_prop',
    'system_boot_reason_prop',
    'system_bootstrap_lib_file',
    'system_data_file',
    'system_data_file',
    'system_data_root_file',
    'system_event_log_tags_file',
    'system_file',  # is this dangerous?
    'system_font_fallback_file',
    'system_group_file',
    'system_jvmti_agent_prop',
    'system_lib_file',
    'system_linker_exec',
    'system_lmk_prop',
    'system_ndebug_socket',
    'system_passwd_file',
    'system_prop',
    'system_seccomp_policy_file',
    'system_security_cacerts_file',
    'system_server',
    'system_suspend',
    'system_suspend_exec',
    'system_trace_prop',
    'system_unsolzygote_socket',
    'system_user_mode_emulation_prop',
    'system_userdir_file',
    'system_zoneinfo_file',
    'systemkeys_data_file',
    'systemsound_config_prop',
    'task_profiles_api_file',
    'task_profiles_file',
    'tcpdump_exec',


    'tee',
    'tee_device',
    'tee_exec',
    'telephony_config_prop',
    'telephony_status_prop',
    'test_boot_reason_prop',
    'test_harness_prop',
    'textclassifier_data_file',
    'theme_prop',
    'threadnetwork_config_prop',
    'time_prop',
    'timezone_metadata_prop',
    'timezone_prop',
    # 'tmpfs',
    'tombstone_config_prop',
    'tombstone_data_file',
    'tombstoned',
    'tombstoned_crash_socket',
    'tombstoned_exec',
    'tombstoned_intercept_socket',
    'tombstoned_java_trace_socket',
    'toolbox_exec',# apatch
    'trace_data_file',
    'traced',
    'traced_consumer_socket',
    'traced_enabled_prop',
    'traced_exec',
    'traced_lazy_prop',
    'traced_oome_heap_session_count_prop',
    'traced_perf_enabled_prop',
    'traced_perf_exec',
    'traced_probes',
    'traced_probes_exec',
    'traced_producer_socket',
    'tty_device',
    'tun_device',#clash meta
    'tuner_config_prop',
    'tuner_server_ctl_prop',
    'ueventd',
    'uhid_device',
    'ultrasound_device',
    'uncrypt_exec',
    'unencrypted_data_file',
    'unlabeled',
    'update_engine_data_file',
    'update_engine_log_data_file',
    'uprobestats_configs_data_file',
    'uprobestats_exec',
    'uprobestats_start_with_config_prop',
    'usb_config_prop',
    'usb_control_prop',
    'usb_prop',
    'usb_uvc_enabled_prop',
    'usbaccessory_device',
    'usbd_exec',
    'use_memfd_prop',
    'user_profile_data_file',
    'user_profile_root_file',
    'userdata_block_device',
    'userdata_sysdev',
    'userdebug_or_eng_prop',
    'usermodehelper',
    'userspace_reboot_config_prop',
    'userspace_reboot_exported_prop',
    'userspace_reboot_log_prop',
    'userspace_reboot_metadata_file',
    'userspace_reboot_test_prop',

    'vdc_exec',
    'vehicle_hal_prop',
    'vendor_adpl_exec',
    'vendor_adsprpc_prop',
    'vendor_adsprpcd',
    'vendor_adsprpcd_exec',
    'vendor_afp_prop',
    'vendor_alarm_boot_prop',
    'vendor_apex_file',
    'vendor_apex_metadata_file',
    'vendor_app_file',
    'vendor_at_device',
    'vendor_atfwd_exec',
    'vendor_audio_data_file',
    'vendor_audio_prop',
    'vendor_audio_socket',
    'vendor_avtimer_device',
    'vendor_batterysecret',
    'vendor_batterysecret_exec',
    'vendor_bluetooth_prop',
    'vendor_boot_mode_prop',
    'vendor_bootreceiver_prop',
    'vendor_boringssl_self_test_exec',
    'vendor_bservice_prop',
    'vendor_bsg_device',
    'vendor_bt_data_file',
    'vendor_bt_device',
    'vendor_camera_data_file',
    'vendor_camera_prop',
    'vendor_cap_configstore_dbg_prop',
    'vendor_cdsprpcd',
    'vendor_cdsprpcd_exec',
    'vendor_cgroup_follow_prop',
    'vendor_cnd',
    'vendor_cnd_data_file',
    'vendor_cnd_exec',
    'vendor_cnd_prop',
    'vendor_cnd_vendor_prop',
    'vendor_configs_file',
    'vendor_console_log_level_prop',
    'vendor_core_ctl_prop',
    'vendor_crash_cnt_prop',
    'vendor_crash_detect_prop',
    'vendor_ctl_netmgrd_prop',
    'vendor_ctl_port-bridge_prop',
    'vendor_ctl_qcrild_prop',
    'vendor_ctl_qmuxd_prop',
    'vendor_ctl_rild_prop',
    'vendor_ctl_vendor_hbtp_prop',
    'vendor_ctl_vendor_imsrcsservice_prop',
    'vendor_ctl_vendor_mmid_prop',
    'vendor_ctl_vendor_rmt_storage_prop',
    'vendor_ctl_vendor_wigigsvc_prop',
    'vendor_data_file',
    'vendor_data_ko_prop',
    'vendor_data_qmipriod_prop',
    'vendor_data_shsusr_prop',
    'vendor_data_tzstorage_file',
    'vendor_dataadpl_prop',
    'vendor_dataqdp_prop',
    'vendor_dataqti_prop',
    'vendor_dataqti_socket',
    'vendor_dbg_brkpoint_prop',
    'vendor_dcvs_prop',
    'vendor_default_prop',
    'vendor_deviceid_prop',
    'vendor_diag_device',
    'vendor_disable_spu_prop',
    'vendor_display_notch_prop',
    'vendor_display_prop',
    'vendor_display_vendor_data_file',
    'vendor_dpmd',
    'vendor_dpmd_data_file',
    'vendor_dpmd_exec',
    'vendor_dpmd_socket',
    'vendor_dpmtcm_socket',
    'vendor_dspservice',
    'vendor_dspservice_exec',
    'vendor_efs_boot_dev',
    'vendor_esoc_device',
    'vendor_exported_odm_prop',
    'vendor_exported_system_prop',
    'vendor_face3d_producer_prop',
    'vendor_fda_prop',
    'vendor_feature_enabler_client',
    'vendor_feature_enabler_client_exec',
    'vendor_file',
    'vendor_fingerprint_prop',
    'vendor_firmware_file',
    'vendor_fm_radio_app_prop',
    'vendor_fst_prop',
    'vendor_gpt_block_device',
    'vendor_gpu_prop',
    'vendor_gralloc_prop',
    'vendor_hal_alarm_qti_default_exec',
    'vendor_hal_capabilityconfigstore_qti_default',
    'vendor_hal_capabilityconfigstore_qti_default_exec',
    'vendor_hal_display_color_default',
    'vendor_hal_display_color_default_exec',
    'vendor_hal_dpmQmiMgr',
    'vendor_hal_dpmQmiMgr_exec',
    'vendor_hal_drm_widevine',
    'vendor_hal_drm_widevine_exec',
    'vendor_hal_esepowermanager_qti',
    'vendor_hal_esepowermanager_qti_exec',
    'vendor_hal_file',
    'vendor_hal_gatekeeper_qti',
    'vendor_hal_gatekeeper_qti_exec',
    'vendor_hal_gnss_qti',
    'vendor_hal_gnss_qti_exec',
    'vendor_hal_imsrtp',
    'vendor_hal_imsrtp_exec',
    'vendor_hal_keymaster_qti',
    'vendor_hal_keymaster_qti_exec',
    'vendor_hal_neuralnetworks_data_file',
    'vendor_hal_neuralnetworks_default',
    'vendor_hal_neuralnetworks_default_exec',
    'vendor_hal_qccvndhal_qti',
    'vendor_hal_qccvndhal_qti_exec',
    'vendor_hal_qseecom_default',
    'vendor_hal_qseecom_default_exec',
    'vendor_hal_qteeconnector_qti',
    'vendor_hal_qteeconnector_qti_exec',
    'vendor_hal_rcsservice_exec',
    'vendor_hal_sensorscalibrate_qti_default',
    'vendor_hal_sensorscalibrate_qti_default_exec',
    'vendor_hal_soter_qti',
    'vendor_hal_soter_qti_exec',
    'vendor_hal_tui_comm_qti',
    'vendor_hal_tui_comm_qti_exec',
    'vendor_hal_usb_qti',
    'vendor_hal_usb_qti_exec',
    'vendor_hvdcp',
    'vendor_hvdcp_exec',
    'vendor_hvdcp_opti_prop',
    'vendor_idc_file',
    'vendor_ims',
    'vendor_ims_exec',
    'vendor_ims_prop',
    'vendor_ims_socket',
    'vendor_init',
    'vendor_init-qcom-sensors-sh_exec',
    'vendor_init-qti-dcvs-sh_exec',
    'vendor_install_recovery_exec',
    'vendor_iop_prop',
    'vendor_ipa_dev',
    'vendor_ipa_vendor_data_file',
    'vendor_ipacm-diag_prop',
    'vendor_ipacm_prop',
    'vendor_irsc_util_exec',
    'vendor_keylayout_file',
    'vendor_km_strongbox_version_prop',
    'vendor_latency_device',
    'vendor_limits_block_device',
    'vendor_lm_data_file',
    'vendor_location',
    'vendor_location_data_file',
    'vendor_location_exec',
    'vendor_location_prop',
    'vendor_location_socket',
    'vendor_mbn_data_file',
    'vendor_mdm_helper',
    'vendor_mdm_helper_exec',
    'vendor_mdm_helper_prop',
    'vendor_mdtp_device',
    'vendor_media_data_file',
    'vendor_mediadrm_vendor_data_file',
    'vendor_mhi_device',
    'vendor_mi_thermald',
    'vendor_mi_thermald_exec',
    'vendor_mlid',
    'vendor_mlid_exec',
    'vendor_mlid_socket',
    'vendor_mm_osal_prop',
    'vendor_mm_parser_prop',
    'vendor_mm_video_prop',
    'vendor_mmi_prop',
    'vendor_modem_diag_prop',
    'vendor_modem_efs_partition_device',
    'vendor_motor_prop',
    'vendor_mpctl_prop',
    'vendor_msm_irqbalance_prop',
    'vendor_msm_irqbalanced',
    'vendor_msm_irqbalanced_exec',
    'vendor_mwqem_prop',
    'vendor_netmgr_data_file',
    'vendor_netmgr_recovery_data_file',
    'vendor_netmgrd',
    'vendor_netmgrd_exec',
    'vendor_netmgrd_socket',
    'vendor_nfc_nq_prop',
    'vendor_nfc_vendor_data_file',
    'vendor_npu_device',
    'vendor_opengles_prop',
    'vendor_overlay_file',
    'vendor_pasr_prop',
    'vendor_pd_locater_dbg_prop',
    'vendor_pd_mapper',
    'vendor_pd_mapper_exec',
    'vendor_pddump_data_file',
    'vendor_per_mgr',
    'vendor_per_mgr_exec',
    'vendor_per_mgr_state_prop',
    'vendor_per_proxy',
    'vendor_per_proxy_exec',
    'vendor_persist_audio_file',
    'vendor_persist_block_device',
    'vendor_persist_camera_file',
    'vendor_persist_camera_prop',
    'vendor_persist_data_file',
    'vendor_persist_display_file',
    'vendor_persist_dpm_prop',
    'vendor_persist_haptics_file',
    'vendor_persist_hvdcp_file',
    'vendor_persist_iar_db_file',
    'vendor_persist_rcs_prop',
    'vendor_persist_rcs_qti_prop',
    'vendor_persist_rfs_file',
    'vendor_persist_rfs_shared_hlos_file',
    'vendor_persist_secnvm_file',
    'vendor_persist_sensors_file',
    'vendor_persist_subsys_file',
    'vendor_persist_tcm_prop',
    'vendor_persist_time_file',
    'vendor_persist_vpp_file',
    'vendor_persist_wcnss_service_file',
    'vendor_port-bridge',
    'vendor_port-bridge_exec',
    'vendor_port-bridge_socket',
    'vendor_port_bridge_data_file',
    'vendor_power_off_alarm_exec',
    'vendor_power_prop',
    'vendor_pps_socket',
    'vendor_proc_audiod',
    'vendor_proc_wifi_dbg',
    'vendor_public_adsprpcd_file',
    'vendor_public_vendor_default_prop',
    'vendor_qcc_prop',
    'vendor_qce_device',
    'vendor_qdcmss_prop',
    'vendor_qdsp_device',
    'vendor_qmipriod',
    'vendor_qmipriod_data_file',
    'vendor_qmipriod_exec',
    'vendor_qmuxd_socket',
    'vendor_qrtr',
    'vendor_qrtr_exec',
    'vendor_qsee_ipc_irq_spss_device',
    'vendor_qspa_prop',
    'vendor_qspm_dbg_prop',
    'vendor_qspm_prop',
    'vendor_qteeconnector_opti_prop',
    'vendor_qtelephony',
    'vendor_qtelephony',
    'vendor_qti',
    'vendor_qti_data_file',
    'vendor_qti_exec',
    'vendor_qti_init_shell_exec',
    'vendor_qtidataservices_app',
    'vendor_qtidataservices_app',
    'vendor_qtidataservices_app',
    'vendor_qvirtmgr_prop',
    'vendor_qvr_external_sensor_device',
    'vendor_qvr_persist_prop',
    'vendor_qvr_prop',
    'vendor_qvrd_persist_prop',
    'vendor_qvrd_prop',
    'vendor_qwes_data_file',
    'vendor_qwesd_socket',
    'vendor_radio_prop',
    'vendor_radio_vendor_data_file',
    'vendor_ramdump_device',
    'vendor_ramdump_microdump_modem_device',
    'vendor_ramdump_prop',
    'vendor_ramdump_vendor_data_file',
    'vendor_reschedule_service_prop',
    'vendor_rfs_access',
    'vendor_rfs_access_exec',
    'vendor_rmnet_device',
    'vendor_rmt_storage_exec',
    'vendor_scroll_prop',
    'vendor_secure_element_vendor_data_file',
    'vendor_security_patch_level_prop',
    'vendor_sensing_vendor_data_file',
    'vendor_sensor_log_data_file',
    'vendor_sensors',
    'vendor_sensors_dbg_prop',
    'vendor_sensors_exec',
    'vendor_sensors_prop',
    'vendor_sensors_qti_exec',
    'vendor_sensors_vendor_data_file',
    'vendor_service_contexts_file',
    'vendor_sg_device',
    'vendor_shell_exec',
    'vendor_shsusr_data_file',
    'vendor_shsusrd',
    'vendor_shsusrd_exec',
    'vendor_skp_device',
    'vendor_slm_prop',
    'vendor_soc_id_prop',
    'vendor_soc_model_prop',
    'vendor_soc_name_prop',
    'vendor_socket_hook_prop',
    'vendor_sp_ssr_device',
    'vendor_spcom_device',
    'vendor_spcomlib_prop',
    'vendor_spss_utils_device',
    'vendor_spunvm_file',
    'vendor_ssd_block_device',
    'vendor_ssgtzd',
    'vendor_ssgtzd_exec',
    'vendor_ssgtzd_socket',
    'vendor_ssr_device',
    'vendor_ssr_prop',
    'vendor_ssr_setup_exec',
    'vendor_sxr_prop',
    'vendor_synx_device',
    'vendor_sys_video_prop',
    'vendor_sysfs_adsp_ssr',
    'vendor_sysfs_battery_supply',
    'vendor_sysfs_bond0',
    'vendor_sysfs_boot_adsp',
    'vendor_sysfs_data',
    'vendor_sysfs_devfreq',
    'vendor_sysfs_devicetree_cpu',
    'vendor_sysfs_devicetree_soc',
    'vendor_sysfs_diag',
    'vendor_sysfs_esoc',
    'vendor_sysfs_fingerprint',
    'vendor_sysfs_gpu_max_clock',
    'vendor_sysfs_graphics',
    'vendor_sysfs_kgsl',
    'vendor_sysfs_kgsl_gpu_model',
    'vendor_sysfs_kgsl_gpubusy',
    'vendor_sysfs_kgsl_gpuclk',
    'vendor_sysfs_kgsl_max_gpuclk',
    'vendor_sysfs_kgsl_proc',
    'vendor_sysfs_kgsl_shell',
    'vendor_sysfs_kgsl_snapshot',
    'vendor_sysfs_mem_offline',
    'vendor_sysfs_mhi',
    'vendor_sysfs_mmc_host',
    'vendor_sysfs_msm_perf',
    'vendor_sysfs_msm_power',
    'vendor_sysfs_msm_subsys_restart',
    'vendor_sysfs_npu',
    'vendor_sysfs_process_reclaim',
    'vendor_sysfs_public',
    'vendor_sysfs_qvr_external_sensor',
    'vendor_sysfs_rmnet',
    'vendor_sysfs_scsi_host',
    'vendor_sysfs_scsi_target',
    'vendor_sysfs_sku',
    'vendor_sysfs_slpi',
    'vendor_sysfs_soc',
    'vendor_sysfs_soc_sensitive',
    'vendor_sysfs_spdaemon',
    'vendor_sysfs_spmi_dev',
    'vendor_sysfs_spss',
    'vendor_sysfs_ssr',
    'vendor_sysfs_ssr_toggle',
    'vendor_sysfs_suspend',
    'vendor_sysfs_system_memory',
    'vendor_sysfs_usb_c',
    'vendor_sysfs_usb_controller',
    'vendor_sysfs_usb_device',
    'vendor_sysfs_usb_supply',
    'vendor_sysfs_usbpd_device',
    'vendor_system_prop',
    'vendor_tee_listener_prop',
    'vendor_thermal-engine_exec',
    'vendor_thermal_data_file',
    'vendor_thermal_normal_prop',
    'vendor_time_daemon',
    'vendor_time_daemon_exec',
    'vendor_time_data_file',
    'vendor_time_service_prop',
    'vendor_tombstone_data_file',
    'vendor_toolbox_exec',# apatch
    'vendor_tui_data_file',
    'vendor_usb_prop',
    'vendor_userdir_file',
    'vendor_video_prop',
    'vendor_vpp_data_file',
    'vendor_vppservice',
    'vendor_vppservice_exec',
    'vendor_wcnss_service',
    'vendor_wcnss_service_exec',
    'vendor_wfd_service_prop',
    'vendor_wfd_sys_debug_prop',
    'vendor_wfd_sys_prop',
    'vendor_wfd_vendor_debug_prop',
    'vendor_wfdservice_exec',
    'vendor_wifi_prop',
    'vendor_wifi_vendor_data_file',
    'vendor_wifi_vendor_wpa_socket',
    'vendor_wifi_version',
    'vendor_wifidisplayhalservice_qti',
    'vendor_wifidisplayhalservice_qti_exec',
    'vendor_wifihal_socket',
    'vendor_wigig_core_prop',
    'vendor_wigig_hostapd_socket',
    'vendor_wigig_prop',
    'vendor_wlan_device',
    'vendor_wlc_prop',
    'vendor_wlc_public_prop',
    'vendor_xbl_block_device',
    'vendor_xdsp_device',
    'vendor_xlat_prop',
    'vendor_xrcb_prop',

    'verity_status_prop',
    'vfat',
    'video_device',
    'virtual_ab_prop',
    'virtual_face_hal_prop',
    'virtual_fingerprint_hal_prop',
    'virtualizationservice_data_file',
    'virtualizationservice_prop',
    'vndbinder_device',
    'vndk_prop',
    'vndservicemanager',
    'vndservicemanager_exec',
    'vold',
    'vold_config_prop',
    'vold_data_file',
    'vold_exec',
    'vold_metadata_file',
    'vold_post_fs_data_prop',
    'vold_prepare_subdirs_exec',
    'vold_prop',
    'vold_status_prop',

    'vpn_data_file',
    'vts_config_prop',
    'vts_status_prop',
    'wallpaper_file',
    'watchdog_metadata_file',
    'watchdogd_exec',
    'webview_zygote',
    'wifi_config_prop',
    'wifi_data_file',
    'wifi_hal_prop',
    'wifi_log_prop',
    'wifi_prop',
    'wificond',
    'wificond_exec',
    'wm_trace_data_file',
    'wpa_data_file',
    'wpa_socket',
    'xtra_control_prop',
    'zero_device',
    'zram_config_prop',
    'zram_control_prop',

    'zygote',
    'zygote_config_prop',
    'zygote_exec',
    'zygote_socket',
    'zygote_wrap_prop',
}
banned_file_owner_operations: set[str] = {
    'file', 'dir', 'lnk_file'
}

# operationsMultiMap = {
# }
# with open('outfile', mode='r') as f2:
#     for l in f2.readlines():
#         if not l.startswith('allow'):
#             continue
#         try:
#             if (l.split(' ')[4]) != '{':
#                 continue
#             j = l.split(' ')[3]
#             i = l.split('{')[1].split('}')[0].split(' ')
#             if j not in operationsMultiMap.keys():
#                 operationsMultiMap[j] = set()
#             for tag in i:
#                 operationsMultiMap[j].add(tag)
#         except:
#             print(l)
# for s in operationsMultiMap.values():
#     assert isinstance(s, set)
#     s.remove('')
# for k in operationsMultiMap.keys():
#     print(k + ':' + str(operationsMultiMap[k]))
setOfDefaultRules:set[str] = set()
fileNames = ['outfile','outfile2']
for fName in fileNames:
    with open(fName,mode='r') as f:
        for line in f.readlines():
            lineArgs = line.split(' ')
            if lineArgs[1] == 'untrusted_app':
                setOfDefaultRules.add(line.replace(lineArgs[0] + ' ' + lineArgs[1],lineArgs[0] + ' ' + 'linearity_trusted_app'))


with open('outfile', mode='r') as f2:
    with open('dat_selinux/sepolicy.rule', mode='w+') as outF:

        outF.write("type linearity_trusted_app domain;\n")
        outF.write("typeattribute linearity_trusted_app appdomain;\n")
        for defaultRule in setOfDefaultRules:
            outF.write(defaultRule)
            if not defaultRule.endswith('\n'):
                outF.write(defaultRule + '\n')
            else:
                outF.write(defaultRule)

        # blacklist_tags_string = "blocked_blacklist"
        # outF.write(f"attribute {blacklist_tags_string}\n\n")
        # for tag in sorted(blacklist_tags):
        #     outF.write(f"typeattribute {tag} blocked_blacklist\n")



        # lines = f2.readlines()
        # for l in lines:
        #     l = l[:-1].split(' ')
        #     if 'untrusted_app' in l[1]:
        #         untrusted_app_names.add(l[1])
        #         if len(l) < 3:
        #             continue
        #         contiFlag = False
        #         if l[2] in whitelists:
        #             continue
        #
        #         # if l[2] in blacklist_tags:
        #         #     print('deny', end=' ', file=outF)
        #         #     for i in l[1:]:
        #         #         print(i, end=' ', file=outF)
        #         #     print(file=outF)
        #         #     contiFlag = True
        #         # if contiFlag:
        #         #     continue
        #         for blackListTagComponent in blacklist_tag_contains:
        #             if blackListTagComponent in l[2]:
        #                 contiFlag = True
        #                 blacklist_tags.add(l[2])
        #                 # print('deny', end=' ', file=outF)
        #                 # for i in l[1:]:
        #                 #     print(i, end=' ', file=outF)
        #                 # print(file=outF)
        #         if contiFlag:
        #             continue
                # print(l)
        # for uname in untrusted_app_names:

        # print('attribute %s'%trust_package_namespace,file=outF)# 1. Define the domain
        # print('type %s, domain'%trust_package_namespace,file=outF)# 1. Define the domain
        # for trusted_package in trusted_packages:
        #     print('genfscon fs=ext4 path=/data/app/%s-*/.* context=u:object_r:%s:s0'%(trusted_package,trust_package_namespace),file=outF)
        #     print('genfscon fs=ext4 path=/data/data/%s/.* context=u:object_r:%s:s0'%(trusted_package,trust_package_namespace),file=outF)

        untrusted_app_names_string = "{ "
        for name in untrusted_app_names:
            untrusted_app_names_string += name + ' '
        untrusted_app_names_string += '}'
        blacklist_tags_string = "{ "
        for name in blacklist_tags:
            blacklist_tags_string += name + ' '
        blacklist_tags_string += '}'
        # for n in blacklist_tags:
        print('deny %s %s * *' % (untrusted_app_names_string,blacklist_tags_string), file=outF)
        # print('deny %s %s * *' % (untrusted_app_names_string,blacklist_tags_string))

        # print('allow %s %s * *' % (trust_package_namespace,blacklist_tags_string), file=outF)
                # print('deny ' + uname + ' ' + n + ' ' + o + ' { ' + operString + '} ', file=outF)
                # banOpers = operationsMultiMap.keys()
                # # banOpers =banned_file_owner_operations
                # for o in banOpers:
                #     operString = ''
                #     for oItem in operationsMultiMap[o]:
                #         operString += oItem + ' '
                #     print('deny ' + uname + ' ' + n + ' ' + o + ' { ' + operString + '} ', file=outF)

# 2. Map APK and app data to that domain


proc = subprocess.Popen("cmd", stdin=subprocess.PIPE)
proc.stdin.write(b'cd dat_selinux\n')
proc.stdin.write(b'7z a -tzip ../datselinux.zip *\n')
proc.communicate()
subprocess.run('adb root')
subprocess.run('adb push datselinux.zip /sdcard/datselinux.zip')
subprocess.run('adb push dat_selinux/sepolicy.rule /data/adb/modules/datselinux/sepolicy.rule')

subprocess.run('adb reboot')
